#!/usr/bin/env bash
# Install nginx on a remote server

apt-get  -y update
apt-get install -y nginx

touch /var/www/html/index.html
echo "Holberton School" > /var/www/html/index.html
printf %s "server {
    listen      80 default_server;
    listen      [::]:80 default_server;
    root        /var/www/html;
    index       index.html index.htm;
    server_name _;
    location / {
            try_files $uri $uri/ =404;
  }
" > /etc/nginx/sites-available/default

service nginx restart
