#!/usr/bin/env bash
# Install nginx on a remote server

apt-get  -y update
apt-get install -y nginx

mv /usr/share/nginx/html/index.html /usr/share/nginx/html/index.txt
echo "Holberton School" > /usr/share/nginx/html/index.html
service nginx restart
