#!/usr/bin/env bash
# Add a custom Nginx response header

apt-get update
apt-get install -y nginx

ufw allow 'Nginx HTTP'
mkdir -p /var/www/html
chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html
touch /var/www/html/404.html
echo -e "Ceci n'est pas une page" > /var/www/html/404.html

SERVER_CONFIG=\
"server {
    listen 80 default_server;
    listen [::]:80 default_server;
    root /var/www/html;
    index index.html index.htm index.nginx-debian.html;
    add_header X-Served-By $HOSTNAME;
    location / {
      proxy_pass http://backend
      try_files \$uri \$uri/ =404;
    }

    location /redirect_me {
    return 301 http://cuberule.com/;
    }

    error_page 404 /404.html;
    location = /404 {
      root /var/www/html/;
      internal;
    }
  }"
bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"

if [ "$(pgrep -c nginx)" -le 0 ]; then
	service nginx start
else
	service nginx restart
fi
