#!/usr/bin/env bash
# Add a custom Nginx response header

apt-get update
apt-get install -y nginx

ufw allow 'Nginx HTTP'
mkdir -p /var/www/html
chmod -R 755 /var/www
echo 'Hello World!' > /var/www/html/index.html
echo -e "Ceci n\x27est pas une page" > /var/www/error/404.html

SERVER_CONFIG=\
"http{
    upstream backend{
      server 3.238.99.252:80
      server 34.232.71.243:80
    }
    server {
      listen 80 default_server;
      listen [::]:80 default_server;
      root /var/www/html;
      index index.html index.htm index.nginx-debian.html;
      server_name 3.238.99.252;
      add_header X-Served-By '37514-web-01';
      location / {
        proxy_pass http://backend
        try_files \$uri \$uri/ =404;
      }

      if (\$request_filename ~ redirect_me){
        rewrite ^ https://sketchfab.com/bluepeno/models permanent;
        }

      error_page 404 /404.html;
      location = /404.html {
        root /var/www/error/;
        internal;
      }
    }

    server {
      listen 80 default_server;
      listen [::]:80 default_server;
      root /var/www/html;
      index index.html index.htm index.nginx-debian.html;
      server_name 34.232.71.243;
      add_header X-Served-By '37514-web-02';
      location / {
        proxy_pass http://backend
        try_files \$uri \$uri/ =404;
      }

      if (\$request_filename ~ redirect_me){
        rewrite ^ https://sketchfab.com/bluepeno/models permanent;
        }

      error_page 404 /404.html;
      location = /404.html {
        root /var/www/error/;
        internal;
      }
    }
  }"
bash -c "echo -e '$SERVER_CONFIG' > /etc/nginx/sites-enabled/default"

if [ "$(pgrep -c nginx)" -le 0 ]; then
	service nginx start
else
	service nginx restart
fi