#!/usr/bin/env bash
# Installs HAProxy version 1.8

apt-get install -y --no-install-recommends software-properties-common
add-apt-repository -y ppa:vbernat/haproxy-2.6
apt-get update
apt-get install -y haproxy=2.6.\*

cp /etc/haproxy/haproxy.cfg /etc/haproxy/haproxy_def.cfg

printf %s "listen balance
    bind *:80
    mode http
    balance roundrobin
    option httpchk
    option forwardfor
    server 37514-web-01 3.238.99.252:80 check
    server 37514-web-02 34.232.71.243:80 check
" >> /etc/haproxy/haproxy.cfg

service haproxy start