#!/usr/bin/env bash
# Ensure Nginx is running and listening on port 80
# of all the server's active IPv4 IPs

sudo apt-get update
sudo apt-get install -y nginx

rm /etc/nginx/sites-available/default
ln -s /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default

sudo service nginx restart

