#!/usr/bin/env bash
# Ensure Nginx is running and listening on port 80
# of all the server's active IPv4 IPs

sudo apt-get update
sudo apt-get install -y nginx

printf %s "server{
	listen 80 default_server;
	listen [::]:80 default_server;
	root /var/www/html;
	index index.html;
	server_name _;

	location / {
		try_files $uri $uri/ =404;
	}
}" > /etc/nginx/sites-available/default

sudo service nginx restart

