#!/usr/bin/env bash
# Configure Nginx to serve a page to a Gunicorn instance listening on port 5000

server {
    listen 80;
    listen [::]:80;
    server_name 100.25.161.104;

    # custom header
    add_header X-Served-By: $hostname;
    
    location = /airbnb-onepage/ {
      proxy_pass http://127.0.0.1:5000;
    }
}
