#!/usr/bin/env bash
# Configure Nginx to serve a a page to a Gunicorn instance on port 5001

printf %s "server
{
  listen 80;
  listen[::]:80;
  server_name 100.25.161.104;

  #custom header
  add_header X-Served-By: $hostname;

  location /airbnb-dynamic/number_odd_or_even/
  {
    proxy_pass http://127.0.0.1:5001;
  }
}" >> /etc/nginx/sites-available/default
