#!/usr/bin/env bash
# Configure Nginx to serve a REST API to a Gunicorn instance on port 5003

printf %s "server
{
  listen 80;
  listen[::]:80;
  server_name 100.25.161.104;

  #custom header
  add_header X-Served-By: $hostname;

  location /
  {
    proxy_pass http://127.0.0.1:5003/2-hbnb;
  }

  location /static
  {
	  proxy_pass http://127.0.0.1:5003;
  }
}" >> /etc/nginx/sites-available/default
